# Copypasta Plugin Configuration

# If enabled_groups is empty and disabled_groups is empty, the plugin is enabled for all groups.
# If enabled_groups is not empty, the plugin is only enabled for those groups.
# Else if disabled_groups is not empty, the plugin is disabled for those groups.

rules:
  - trigger: ""
    response: ""
    enabled_groups:
      - 123456789
    disabled_groups: []
    enable_pm: false
